# Generated by Django 3.2 on 2021-10-13 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=254, null=True, verbose_name='Description')),
                ('range_days', models.IntegerField(blank=True, null=True, verbose_name='Range')),
            ],
            options={
                'verbose_name_plural': 'Pair',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('mms', models.CharField(blank=True, max_length=254, null=True, verbose_name='MMS')),
                ('timestamp', models.CharField(blank=True, max_length=254, null=True, verbose_name='Timestamp')),
                ('pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.pair', verbose_name='Pair')),
            ],
            options={
                'verbose_name_plural': 'Price',
            },
        ),
    ]
